# 主にdevコンテナの利用と、docker runコマンドの再現性を目的として、１コンテナのみですがcomposeを利用しています
services:
  v-schedule:
    image: "v-schedule"
    container_name: "v-schedule"
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/v-schedule
      - ${HOME}/.ssh:/home/node/.ssh
    ports:
      - "5100:3000"
    environment:
      - TZ=Asia/Tokyo
